# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b7bb80fc118e9017202662f0bbc20eb4c0094705ed4bd8589318644b96eec0333e3d79a8029172d72eb4a35ef4aadb9a2caa317949ed6dd459aa17f4289073a

test:
  secret_key_base: 42f82caa9636cc3980a928028e19b6e58fd57d71095bd36cfe678d855545629f5f780b5521d4bb32329b6076f858ab452845c8a07c24c869650b7e55c46add65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
